version: '3.6'

services:
  mailserver:
    image: daone/postfix-dovecot
    container_name: mailserver
    restart: unless-stopped
    ports:
     - 25:25
     - 465:465
     - 143:143
     - 993:993
    environment:
     - maildomain=devlmu.com
    volumes:
     - /path_for_postfix_mail_delivery:/var/mail
     - /path_for_imap_storage:/home
