version: '3.6'

services:
  mailserver:
    hostname: mail-server-roundcube
    image: marooou/postfix-roundcube
    container_name: roundserver
    restart: unless-stopped
    ports:
     - 25:25
     - 110:110
     - 143:143
     - 465:465
     - 993:993
     - 995:995
    environment:
     - ADMIN_USERNAME=root
     - ADMIN_PASSWD=password
     - DOMAIN_NAME=devlmu.com
     - USERS=abay:abay-1,bayu:bayu-1
    volumes:
     - /data/mysql:/var/lib/mysql
     - /data/vmail/:/var/vmail
     - /data/log:/var/log
